-- 收入表 - 保存所有收入记录
CREATE TABLE IF NOT EXISTS income (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATETIME NOT NULL COMMENT '收入日期时间',
    category VARCHAR(50) NOT NULL COMMENT '收入类别',
    description VARCHAR(255) COMMENT '描述',
    amount DECIMAL(10,2) NOT NULL COMMENT '金额',
    status VARCHAR(20) DEFAULT 'PAID' COMMENT '状态（PAID已付款/PENDING待付款）',
    booking_id INT COMMENT '关联预订ID',
    synced BOOLEAN DEFAULT FALSE COMMENT '是否已同步',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
); 